name: Go Test

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      cache-go-dependencies:
        default: false
        required: false
        type: boolean

jobs:
  test:
    strategy:
      matrix:
        go-version: ["${{inputs.go-version}}"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: ${{inputs.cache-go-dependencies}}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: go test ./...
